#!/bin/bash

source venv/bin/activate

# check that no pending DB changes
python manage.py migrate | grep makemigrations
if [ "$?" == "0" ]; then
    echo "Pending DB changes, run python manage.py makemigrations and commit changes first"
    exit 1
fi

# automatic tests
dt -q
python manage.py test
if [ "$?" != "0" ]; then
    echo "Automatic tests reported problems, terminating release"
    exit 1
fi
echo "Automatic tests ok (`dt -q -d`), proceeding..."

# prospector
dt -q
prospector -i htmlcov
if [ "$?" != "0" ]; then
    echo "Prospector reported problems, terminating release"
    exit 1
fi
echo "Prospector cleared build (`dt -q -d`), proceeding..."

# mypy
dt -q
mypy .
if [ "$?" != "0" ]; then
    echo "Mypy reported problems, terminating release"
    exit 1
fi
echo "Mypy cleared build (`dt -q -d`), proceeding..."

# pytype
dt -q
pytype --config pytype.cfg
if [ "$?" != "0" ]; then
    echo "Pytype reported problems, terminating release"
    exit 1
fi
echo "Pytype cleared build (`dt -q -d`), proceeding..."

echo "Pre-release script ok"
exit 0
