#!/bin/bash

source venv/bin/activate
coverage run --source='.' --omit='*/venv/*,project/*,setup.py,**/migrations/*' manage.py test
if [ "$1" == "--codecov" ]; then
    codecov -X gcov
fi
coverage report --skip-empty --skip-covered -m

