# Generated by Django 2.0 on 2018-02-08 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("jacc", "0010_auto_20180201_0734"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountentry",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="accountentry_set",
                to="jacc.Account",
                verbose_name="record account",
            ),
        ),
    ]
