# Generated by Django 3.2 on 2021-04-22 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jacc", "0023_accountentrynote"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountentry",
            name="cached_balance",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=10, null=True, verbose_name="balance"
            ),
        ),
    ]
