# Generated by Django 3.2 on 2021-04-23 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jacc", "0025_account_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountentry",
            name="cached_balance",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=16, null=True, verbose_name="balance"
            ),
        ),
    ]
