# Generated by Django 3.2 on 2021-04-24 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jacc", "0026_alter_accountentry_cached_balance"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accountentry",
            name="cached_balance",
        ),
    ]
